### PR TITLE
Expose configured properties (authHeader and urlBase) on LoopBackResource

### PR DESCRIPTION
**Pull request by mrbatista**
@bajtos  please review. Mention me in your comment if it needs rework. This PR is related to the improvement discussed in the very old PR #90.

### CODE REVIEW

**Comment by bajtos** [comment]
@mrbatista thank you for the pull request. The code changes looks good to me, please fix the commit message to follow the [50/72 rule](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). That should fix the following CI failure:

>  Commit Linter — commits in this PR have formatting problems 

The other failures seem to be intermittent, don't worry about them.

**Comment by mrbatista** [comment]
@bajtos fixed! Please review again. Thanks.

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Comment by mrbatista** [comment]
@bajtos when will this enhancement be published to npm?

**Comment by mrbatista** [comment]
ping @bajtos

**Comment by bajtos** [comment]
@mrbatista sorry for the delay, your enhancement is available in version `1.8.0`

**Pull request merged**
