### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by gausie**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@gausie thank you for the pull request. Are you actually using this module via Bower? Our preferred distribution channel is `npm`. We use bower to fetch front-end dependencies only. However, since most front-end libraries are already available on npm too, I'd prefer to get rid of `bower.json` entirely.

Thoughts?

**Comment by gausie** [comment]
I use npm also, I just noticed the inconsistency so submitted a patch for
those who do!

**Comment by bajtos** [comment]
Closing in favour of #207.

BTW bower's `version` fields is deprecated, people should use Git tags instead (see [bower docs](https://github.com/bower/spec/blob/master/json.md#version)).

**Pull request closed without merging**
