### PR TITLE
Apply helmet

### PR DESCRIPTION
**Pull request by kennethlynne**
Fix https://github.com/strongloop/loopback-sdk-angular/issues/159

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by kennethlynne** [comment]
This yields:

```bash
Loading LoopBack app "...api/server/server.js"
No providers specified for the environment undefined
Generating "SDK" for the API endpoint "http://localhost:1337/api"
Warning: scope ETUser.spaces is missing _targetClass property.
The Angular code for this scope won't be generated.
Please upgrade to the latest version of
loopback-datasource-juggler to fix the problem.
```

Improvement over crashing at least.

**Comment by kennethlynne** [comment]
Also, removing '__get__' from the method name fixed it

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @kennethlynne, thank you for the pull request. I am closing this PR in favour of #168, where I improved your patch by adding unit-test and rewording the commit message into a more descriptive one.

**Pull request closed without merging**
