### PR TITLE
Clear data logout interceptor

### PR DESCRIPTION
**Pull request by mrbatista**
Clear user data if method login return error response.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@mrbatista thank you for the pull request. Please add a unit test to verify the implementation and prevent regressions in the future.

**Comment by mrbatista** [comment]
@bajtos unit test added. Related issue #197.

**Comment by loay** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@mrbatista the code looks good to me now, thank you.

However, I have one concern - is it a good idea to clear auth data when logout fails? Doesn't it mean that the logout operation was not finished and thus the user may be still logged in?

**Comment by noderat** [comment]
@bajtos I can see your point, however, if a user is **intentionally** logging out and either their token is expired already or their internet connection has failed it's probably a good idea to clear the localstorage anyway and just allow the token to expire naturally. Perhaps add a force argument (boolean) that toggles clearing local storage?

**Comment by bajtos** [comment]
Fair enough. I have landed this patch via 4dcf971, thank you for the contribution!

**Pull request closed without merging**
