### PR TITLE
Fix substring on undefined url

### PR DESCRIPTION
**Pull request by acourtiol**
Remove "TypeError: Cannot read property 'substr' of undefined" error

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jdrouet** [comment]
:+1: Again, can one of the admins verify this patch and merge it ? That would be great...

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
The code change LGTM, could you please add a unit-test to verify the implementation?

**Comment by bajtos** [comment]
I am closing this pull request as it looks abandoned. Feel free to reopen once you find time to add a unit-test to verify the implementation, as commented above.

**Pull request closed without merging**
