### PR TITLE
fixed the hard coded 'lbServices' in the documentation

### LINKED ISSUE #172: documentations is broken when giving custom module name
If I config in the task ngModuleName that is not lbServices, the docs generatedare not valid as some of the services / methods use the module i gave and some of them use 'lbServices'

### PR DESCRIPTION
**Pull request by ezraroi**
[Review on Reviewable](https://reviewable.io/reviews/strongloop/loopback-sdk-angular/173)

Fix #172

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Comment by bajtos** [comment]
Released in 1.5.0.

**Pull request merged**
