### PR TITLE
Update dependency and test command for PhantomJS

### PR DESCRIPTION
**Pull request by scalarsys**
The resolution to an error when running "npm test" is to update the PhantomJS dependency to PhantomJS2.

## Background

Current angular dependency is defined:
  "angular": "^1.4.9"

With the release of angular 1.5 there are errors loading angular in PhantomJS that affect this repo's default test command.

Original Issue not addressed in PhantomJS 1.0: https://github.com/ariya/phantomjs/issues/10522

Recent discussion specific to angular 1.5: https://github.com/angular/angular.js/issues/13794

Error Message:
> PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
>   Error: [$injector:modulerr] Failed to instantiate module ng due to:
>   TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by davidcheung** [comment]
@slnode okay to test

**Comment by davidcheung** [comment]
I can confirm that the current phantomJS doesnt install properly, you need to change `https` from npm registry to `npm set registry http://registry.npmjs.org/` or else it wouldnt download the package

**Comment by davidcheung** [comment]
@scalarsys Thanks for the patch!
and can you please sign the CLA agreement

**Comment by scalarsys** [comment]
I have signed the CLA but had problems with SL team members seeing that I have signed it on another PR. When I go to https://cla.strongloop.com/agreements if shows that I have signed the agreement for loopback-sdk-angular. Let me know if you need me to do anything to clear up the CLA issue.

**Comment by davidcheung** [comment]
Oh, I believe its because the commit it under @jeff-clegg, therefore the CLA check isnt passing.

**Comment by jeff-clegg** [comment]
Ok, my mistake, I signed CLA as @jeff-clegg.

**Comment by davidcheung** [comment]
@scalarsys would you be able to rebase the changes on top of current master please?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by scalarsys** [comment]
Not sure if I did the rebase correctly, sorry if this is too much trouble.

**Comment by davidcheung** [comment]
sorry my fault, since I took so long to reply, might have been a better idea to just fetch the latest and redo it on the origin/master. 
@scalarsys i am rerunning the CI on this PR https://github.com/strongloop/loopback-sdk-angular/pull/231

**Comment by davidcheung** [comment]
@scalarsys Thanks for your PR i have landed via #231

**Pull request closed without merging**
