### PR TITLE
Add translated files

### PR DESCRIPTION
**Pull request by davidcheung**
connect to https://github.com/strongloop-internal/scrum-loopback/issues/1070

### CODE REVIEW

**Comment by davidcheung** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@0candy PTAL

**Comment by 0candy** [comment]
I thought @bajtos said we shouldn't be getting the strong-arc error anymore?

**Comment by bajtos** [comment]
> I thought @bajtos said we shouldn't be getting the strong-arc error anymore?

I checked [CI results](http://ci.strongloop.com/job/strong-arc/4303/), only 2 out of 10 (12?) platforms failed. Both failures are caused by https://github.com/strongloop/strong-mesh-client/issues/50, the indication is "Failed to install dependencies."

**Pull request merged**
