### PR TITLE
added model naming strategies

### PR DESCRIPTION
**Pull request by jmls**
added the ability to specify the model naming strategy for the loopback services models
there are three options:
"upperCaseFirst" (default / current behaviour): changes customer to Customer, foo_bar to Foo_bar
"pascalCase" : changes customer to Customer, foo_bar to FooBar
"camelCase" : changes customer to customer, foo_bar to fooBar

this option is specified by the -c option on the lb-ng command

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @jmls, thank you for the pull request. First of all, please add unit-tests to verify the new feature.

Secondly, I prefer to keep the number of configuration options low. Let's make a focused change to fix the problem you mentioned in the [mailing list](https://groups.google.com/d/topic/loopbackjs/G82ZBgsxM1g/discussion) and provide a behaviour consistent with the server code.

**Comment by jmls** [comment]
hi @bajtos , I did add some tests to the loopback-angular-sdk-cli repo - there are several tests in there pertaining to this repo

whilst I understand the need to keep options down, I did it this way purely so that there would be 100% backwards compatibility with any project that is currently using lb-services. In other words, existing projects won't be affected by this change, but any new project can take advantage of the new options

**Comment by bajtos** [comment]
> I did it this way purely so that there would be 100% backwards compatibility with any project that is currently using lb-services. In other words, existing projects won't be affected by this change, but any new project can take advantage of the new options

Good point, backwards compatibility is pretty important. On the other hand, I would expect there are not many people using the ugly underscore-based names, thus the change should not affect too big group.

I am inclining towards implementing this fix as a breaking change and make a 2.x release.

Thoughts?

**Comment by bajtos** [comment]
@jmls ping, are you still keen to finish up this patch and get it landed?

**Comment by jmls** [comment]
hi @bajtos, for sure I want to land it ;) What do you need ?

Is the only issue the fact that it's another option ? I would prefer to retain compatibility, but understand if you want to make it a breaking change.

Just thought that it may be nice to allow people the option of choosing how they want their angular models named

**Comment by bajtos** [comment]
> Is the only issue the fact that it's another option ? I would prefer to retain compatibility, but understand if you want to make it a breaking change.

Yes please, let's drop the option and always build PascalCase names. The model resources are conceptually classes and the JavaScript convention is to give PascalCase names to classes AFAIK.

> Just thought that it may be nice to allow people the option of choosing how they want their angular models named

I have two problems with that:
 - It adds more code that we have to maintain.
 - Users need to learn about more config settings, it takes more work to get the configuration right.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Also please add a unit-test to verify and document how a model name "foo_bar" is handled. While you are at that, I would appreciate if you added a test for "foo-bar" too.

**Comment by bajtos** [comment]
Once we land and release this pull request as 2.0, we will need to update dependencies in CLI, Grunt and Gulp plugins and release a 2.0 versions of them too.

**Comment by bajtos** [comment]
@jmls ping, is this pull request still alive?

**Comment by jmls** [comment]
it is still alive .. :)

**Comment by bajtos** [comment]
@jmls ping, so what's the plan? I'd like to land the fix for "foo_bar" at some point, preferably via the backwards-incompatible change.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
I am closing this pull request as abandoned, feel free to reopen it if/when you have time to finish this contribution.

**Pull request closed without merging**
