### PR TITLE
Add loopBackResourceProvider.getUrlBase()

### PR DESCRIPTION
**Pull request by jsheely**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @jsheely, thank you for the contribution. Please add ngdoc-style comment to your new method and a unit-test to verify the implementation - see [existing tests](https://github.com/strongloop/loopback-sdk-angular/blob/eeac49cc8cbae48d13dbd04a36d7b6c526dd5780/test.e2e/spec/services.spec.js#L115-L136) for inspiration.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by jsheely** [comment]
ngDoc comment and spec test added.

**Comment by bajtos** [comment]
Landed via 9915b8a, I have removed the misleading comment in the new test and fixed coding style (trailing whitespace).

Thank you for the contribution!

**Comment by bajtos** [comment]
Released in 1.5.0.

**Pull request closed without merging**
